//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AgTwo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.6.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setUDP_isOn {
            get {
                return ((bool)(this["setUDP_isOn"]));
            }
            set {
                this["setUDP_isOn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("29999")]
        public int setIP_thisPort {
            get {
                return ((int)(this["setIP_thisPort"]));
            }
            set {
                this["setIP_thisPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("28888")]
        public int setIP_autoSteerPort {
            get {
                return ((int)(this["setIP_autoSteerPort"]));
            }
            set {
                this["setIP_autoSteerPort"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setPgm_isFirstRun {
            get {
                return ((bool)(this["setPgm_isFirstRun"]));
            }
            set {
                this["setPgm_isFirstRun"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setPgm_defaultLat {
            get {
                return ((double)(this["setPgm_defaultLat"]));
            }
            set {
                this["setPgm_defaultLat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setPgm_defaultLon {
            get {
                return ((double)(this["setPgm_defaultLon"]));
            }
            set {
                this["setPgm_defaultLon"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("en")]
        public string setF_culture {
            get {
                return ((string)(this["setF_culture"]));
            }
            set {
                this["setF_culture"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Default")]
        public string setF_workingDirectory {
            get {
                return ((string)(this["setF_workingDirectory"]));
            }
            set {
                this["setF_workingDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setGPS_SimLatitude {
            get {
                return ((double)(this["setGPS_SimLatitude"]));
            }
            set {
                this["setGPS_SimLatitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public double setGPS_SimLongitude {
            get {
                return ((double)(this["setGPS_SimLongitude"]));
            }
            set {
                this["setGPS_SimLongitude"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string setComm_commName {
            get {
                return ((string)(this["setComm_commName"]));
            }
            set {
                this["setComm_commName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setUDP_isSendNMEAToUDP {
            get {
                return ((bool)(this["setUDP_isSendNMEAToUDP"]));
            }
            set {
                this["setUDP_isSendNMEAToUDP"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool setUDP_isUsePluginApp {
            get {
                return ((bool)(this["setUDP_isUsePluginApp"]));
            }
            set {
                this["setUDP_isUsePluginApp"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMod_isNavConnected {
            get {
                return ((bool)(this["setMod_isNavConnected"]));
            }
            set {
                this["setMod_isNavConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMod_isMachineConnected {
            get {
                return ((bool)(this["setMod_isMachineConnected"]));
            }
            set {
                this["setMod_isMachineConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool setMod_isSteerConnected {
            get {
                return ((bool)(this["setMod_isSteerConnected"]));
            }
            set {
                this["setMod_isSteerConnected"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("192")]
        public byte etIP_SubnetOne {
            get {
                return ((byte)(this["etIP_SubnetOne"]));
            }
            set {
                this["etIP_SubnetOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("168")]
        public byte etIP_SubnetTwo {
            get {
                return ((byte)(this["etIP_SubnetTwo"]));
            }
            set {
                this["etIP_SubnetTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public byte etIP_SubnetThree {
            get {
                return ((byte)(this["etIP_SubnetThree"]));
            }
            set {
                this["etIP_SubnetThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("127")]
        public byte eth_loopOne {
            get {
                return ((byte)(this["eth_loopOne"]));
            }
            set {
                this["eth_loopOne"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte eth_loopTwo {
            get {
                return ((byte)(this["eth_loopTwo"]));
            }
            set {
                this["eth_loopTwo"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte eth_loopThree {
            get {
                return ((byte)(this["eth_loopThree"]));
            }
            set {
                this["eth_loopThree"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255")]
        public byte eth_loopFour {
            get {
                return ((byte)(this["eth_loopFour"]));
            }
            set {
                this["eth_loopFour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Setting {
            get {
                return ((string)(this["Setting"]));
            }
            set {
                this["Setting"] = value;
            }
        }
    }
}
